# Generated by Django 4.2.30 on 2026-06-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentplatform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_platforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='investmentsnapshot',
            index=models.Index(fields=['user', 'year', 'month'], name='investments_user_id_0dfac2_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmentsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'month', 'year', 'category', 'platform'), name='unique_investment_snapshot'),
        ),
    ]
