# Generated by Django 4.2.30 on 2026-06-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentplatform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
