# Generated by Django 4.2.30 on 2026-06-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplatform',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='investments.investmentcategory'),
        ),
    ]
