# Generated by Django 4.2.30 on 2026-07-02 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0004_investmentplatform_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentSnapshotAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='investmentsnapshot',
            name='unique_investment_snapshot',
        ),
        migrations.AlterField(
            model_name='investmentsnapshot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.investmentcategory'),
        ),
        migrations.AddConstraint(
            model_name='investmentsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'month', 'year', 'platform'), name='unique_investment_snapshot'),
        ),
        migrations.AddField(
            model_name='investmentsnapshotasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_associations', to='investments.asset'),
        ),
        migrations.AddField(
            model_name='investmentsnapshotasset',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_assets', to='investments.investmentsnapshot'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='investments.investmentcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='investmentsnapshotasset',
            constraint=models.UniqueConstraint(fields=('snapshot', 'asset'), name='unique_snapshot_asset'),
        ),
    ]
