# Generated by Django 4.2.30 on 2026-07-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_asset_investmentsnapshotasset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplatform',
            name='category',
        ),
    ]
