# Generated by Django 4.2.30 on 2026-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
