# Generated by Django 4.2.30 on 2026-07-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
