# Generated by Django 4.2.30 on 2026-07-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_migrate_account_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='type',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banking.accounttype'),
        ),
    ]
