# Generated by Django 4.2.30 on 2026-06-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilitysnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liabilitycategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liability_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lender',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lenders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='liabilitysnapshot',
            index=models.Index(fields=['user', 'year', 'month'], name='liabilities_user_id_ba0d32_idx'),
        ),
        migrations.AddConstraint(
            model_name='liabilitysnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'month', 'year', 'category', 'lender'), name='unique_liability_snapshot'),
        ),
    ]
