# Generated by Django 4.2.30 on 2026-06-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lenders', to='liabilities.liabilitycategory'),
        ),
        migrations.AddField(
            model_name='lender',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liabilitycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
