# Generated by Django 4.2.30 on 2026-06-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0003_lender_category_lender_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='original_loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
