# Generated by Django 4.2.30 on 2026-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0004_lender_original_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
