# Generated by Django 4.2.30 on 2026-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0005_lender_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
