# Generated by Django 4.2.30 on 2026-07-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0006_lender_end_date_lender_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_fixed_interest', models.BooleanField(default=True)),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('subscription_id', models.IntegerField(blank=True, null=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liabilities.lender')),
            ],
        ),
    ]
